import { CalculatorId, CurrencyCode } from '../types/financial';

export interface MarketBenchmark {
  id: string;
  label: string;
  shortLabel: string;
  val: string;
  numericVal: number;
  unit: string;
  target: CalculatorId;
  source: string;
  sourceShort: string;
  frequency: string;
  patchInputs: Record<string, any>;
  description: string;
}

export interface RegionalMarketData {
  regionName: string;
  shortTag: string;
  sourceSummary: string;
  benchmarks: MarketBenchmark[];
}

export const REGIONAL_MARKET_DATA: Record<CurrencyCode, RegionalMarketData> = {
  USD: {
    regionName: 'United States',
    shortTag: 'US Market Rates',
    sourceSummary: 'Freddie Mac PMMS & Federal Reserve H.15',
    benchmarks: [
      {
        id: 'usd-30y-mortgage',
        label: '30-Yr Fixed Mortgage',
        shortLabel: '30-Yr Mort.',
        val: '6.62%',
        numericVal: 6.62,
        unit: '%',
        target: 'mortgage',
        source: 'Freddie Mac PMMS Weekly National Average',
        sourceShort: 'Freddie Mac',
        frequency: 'Weekly (Every Thu)',
        patchInputs: { interestRate: 6.62, loanTermYears: 30 },
        description: 'US nationwide standard for 30-year fixed home purchase loans.',
      },
      {
        id: 'usd-15y-mortgage',
        label: '15-Yr Fixed Mortgage',
        shortLabel: '15-Yr Mort.',
        val: '5.89%',
        numericVal: 5.89,
        unit: '%',
        target: 'mortgage',
        source: 'Freddie Mac PMMS Weekly National Average',
        sourceShort: 'Freddie Mac',
        frequency: 'Weekly (Every Thu)',
        patchInputs: { interestRate: 5.89, loanTermYears: 15 },
        description: 'Accelerated home equity benchmark with lower lifetime interest cost.',
      },
      {
        id: 'usd-prime-rate',
        label: 'Fed Funds / Prime Rate',
        shortLabel: 'Fed Prime',
        val: '8.00%',
        numericVal: 8.0,
        unit: '%',
        target: 'loan',
        source: 'Federal Reserve H.15 Selected Interest Rates',
        sourceShort: 'Federal Reserve',
        frequency: 'FOMC Schedule',
        patchInputs: { interestRate: 8.0, termYears: 5 },
        description: 'US commercial bank benchmark for personal loans, HELOCs, and credit lines.',
      },
      {
        id: 'usd-sp500-return',
        label: 'S&P 500 Historical Avg',
        shortLabel: 'S&P 500',
        val: '10.2%',
        numericVal: 10.2,
        unit: '%',
        target: 'investment',
        source: 'S&P Dow Jones Indices (1926–Present with dividends reinvested)',
        sourceShort: 'S&P Dow Jones',
        frequency: 'Annual CAGR',
        patchInputs: { annualReturn: 10.2, compoundingFrequency: 12 },
        description: 'Long-term compound annual growth rate of the 500 largest US public corporations.',
      },
      {
        id: 'usd-401k-limit',
        label: '401(k) Employee Cap',
        shortLabel: '401(k) Cap',
        val: '$23,000',
        numericVal: 23000,
        unit: '$',
        target: 'retirement',
        source: 'IRS Section 402(g) Elective Deferral Limit',
        sourceShort: 'IRS Notice',
        frequency: 'Annual IRS Notice',
        patchInputs: { contributionPercent: 12, currentSalary: 95000 },
        description: 'Maximum annual tax-advantaged employee contribution allowed under US law.',
      },
      {
        id: 'usd-cpi-inflation',
        label: 'US CPI-U Inflation',
        shortLabel: 'US CPI',
        val: '2.9%',
        numericVal: 2.9,
        unit: '%',
        target: 'inflation',
        source: 'US Bureau of Labor Statistics (BLS) Consumer Price Index',
        sourceShort: 'BLS CPI-U',
        frequency: 'Monthly Release',
        patchInputs: { inflationRate: 2.9 },
        description: 'Headline 12-month change in the Consumer Price Index for all urban consumers.',
      },
    ],
  },

  PKR: {
    regionName: 'Pakistan',
    shortTag: 'Pakistan Market Rates',
    sourceSummary: 'State Bank of Pakistan (SBP) & KIBOR',
    benchmarks: [
      {
        id: 'pkr-kibor',
        label: '6-Month KIBOR Benchmark',
        shortLabel: '6M KIBOR',
        val: '14.85%',
        numericVal: 14.85,
        unit: '%',
        target: 'loan',
        source: 'State Bank of Pakistan / Financial Markets Association',
        sourceShort: 'SBP KIBOR',
        frequency: 'Daily Interbank Rate',
        patchInputs: { interestRate: 14.85, loanTermMonths: 60 },
        description: 'Karachi Interbank Offered Rate used as benchmark for all floating bank loans in Pakistan.',
      },
      {
        id: 'pkr-sbp-policy',
        label: 'SBP Monetary Policy Rate',
        shortLabel: 'SBP Policy',
        val: '15.00%',
        numericVal: 15.0,
        unit: '%',
        target: 'loan',
        source: 'State Bank of Pakistan (SBP) Monetary Policy Committee',
        sourceShort: 'SBP MPC',
        frequency: 'Bi-Monthly Review',
        patchInputs: { interestRate: 15.0, loanTermMonths: 36 },
        description: 'Official central bank target policy rate of Pakistan.',
      },
      {
        id: 'pkr-home-finance',
        label: 'Home Loan Finance (KIBOR+Spread)',
        shortLabel: 'Home Finance',
        val: '16.50%',
        numericVal: 16.5,
        unit: '%',
        target: 'mortgage',
        source: 'Commercial Banks (HBL, Meezan, Bank Alfalah average)',
        sourceShort: 'Commercial Banks',
        frequency: 'Monthly Retail Average',
        patchInputs: { interestRate: 16.5, loanTermYears: 20 },
        description: 'Average mortgage / housing finance markup rate across Pakistani commercial & Islamic banks.',
      },
      {
        id: 'pkr-psx',
        label: 'KSE-100 Index Historical Return',
        shortLabel: 'PSX KSE-100',
        val: '15.2%',
        numericVal: 15.2,
        unit: '%',
        target: 'investment',
        source: 'Pakistan Stock Exchange (PSX) 10-Yr Historical CAGR',
        sourceShort: 'PSX Index',
        frequency: 'Multi-Year Average',
        patchInputs: { interestRate: 15.2, compoundFrequency: 'annually' },
        description: 'Long-term equity market return of the Karachi Stock Exchange KSE-100 index.',
      },
      {
        id: 'pkr-cpi',
        label: 'Pakistan CPI Inflation',
        shortLabel: 'PBS Inflation',
        val: '9.6%',
        numericVal: 9.6,
        unit: '%',
        target: 'inflation',
        source: 'Pakistan Bureau of Statistics (PBS)',
        sourceShort: 'PBS National CPI',
        frequency: 'Monthly Release',
        patchInputs: { annualInflationRate: 9.6 },
        description: 'Headline year-on-year National Consumer Price Index reported by PBS.',
      },
    ],
  },

  INR: {
    regionName: 'India',
    shortTag: 'India Market Rates',
    sourceSummary: 'Reserve Bank of India (RBI) & SBI',
    benchmarks: [
      {
        id: 'inr-home-loan',
        label: 'SBI / HDFC Home Loan Rate',
        shortLabel: 'Home Loan',
        val: '8.50%',
        numericVal: 8.5,
        unit: '%',
        target: 'mortgage',
        source: 'State Bank of India (SBI) / HDFC Bank EBLR Benchmark',
        sourceShort: 'SBI Benchmark',
        frequency: 'Monthly Retail Lending Rate',
        patchInputs: { interestRate: 8.5, loanTermYears: 20 },
        description: 'Standard floating home loan interest rate benchmark for prime borrowers in India.',
      },
      {
        id: 'inr-rbi-repo',
        label: 'RBI Repo Rate',
        shortLabel: 'RBI Repo',
        val: '6.50%',
        numericVal: 6.5,
        unit: '%',
        target: 'loan',
        source: 'Reserve Bank of India (RBI) Monetary Policy Committee',
        sourceShort: 'RBI MPC',
        frequency: 'Bi-Monthly MPC',
        patchInputs: { interestRate: 6.5, loanTermMonths: 36 },
        description: 'Key policy repo rate set by the Reserve Bank of India governing all retail EBLR loans.',
      },
      {
        id: 'inr-nifty',
        label: 'NIFTY 50 Historical Return',
        shortLabel: 'NIFTY 50',
        val: '12.8%',
        numericVal: 12.8,
        unit: '%',
        target: 'investment',
        source: 'National Stock Exchange (NSE India) 15-Yr TRI CAGR',
        sourceShort: 'NSE Nifty',
        frequency: 'Long-Term CAGR',
        patchInputs: { interestRate: 12.8, compoundFrequency: 'monthly' },
        description: 'Historical compound annual growth rate of the Nifty 50 Total Returns Index.',
      },
      {
        id: 'inr-ppf',
        label: 'Public Provident Fund (PPF)',
        shortLabel: 'PPF Rate',
        val: '7.10%',
        numericVal: 7.1,
        unit: '%',
        target: 'investment',
        source: 'Ministry of Finance, Government of India',
        sourceShort: 'Govt Small Savings',
        frequency: 'Quarterly Notification',
        patchInputs: { interestRate: 7.1, compoundFrequency: 'annually' },
        description: 'Government of India backed sovereign tax-free long-term savings return under Sec 80C.',
      },
      {
        id: 'inr-cpi',
        label: 'India CPI Headline Inflation',
        shortLabel: 'India CPI',
        val: '5.4%',
        numericVal: 5.4,
        unit: '%',
        target: 'inflation',
        source: 'Ministry of Statistics & Programme Implementation (MoSPI)',
        sourceShort: 'MoSPI CPI',
        frequency: 'Monthly Data',
        patchInputs: { annualInflationRate: 5.4 },
        description: 'Retail inflation measured by the Consumer Price Index (Combined) in India.',
      },
    ],
  },

  GBP: {
    regionName: 'United Kingdom',
    shortTag: 'UK Market Rates',
    sourceSummary: 'Bank of England (BoE) & ONS',
    benchmarks: [
      {
        id: 'gbp-boe-base',
        label: 'Bank of England Base Rate',
        shortLabel: 'BoE Base',
        val: '5.00%',
        numericVal: 5.0,
        unit: '%',
        target: 'loan',
        source: 'Bank of England Monetary Policy Committee (MPC)',
        sourceShort: 'BoE MPC',
        frequency: '6-Week MPC Cycle',
        patchInputs: { interestRate: 5.0, loanTermMonths: 48 },
        description: 'Official Bank Rate set by the Bank of England determining UK lending and savings costs.',
      },
      {
        id: 'gbp-5y-fixed',
        label: 'UK 5-Yr Fixed Mortgage',
        shortLabel: '5-Yr Mort.',
        val: '4.65%',
        numericVal: 4.65,
        unit: '%',
        target: 'mortgage',
        source: 'Bank of England Quoted Household Interest Rates',
        sourceShort: 'BoE Quoted',
        frequency: 'Monthly Average',
        patchInputs: { interestRate: 4.65, loanTermYears: 25 },
        description: 'Average rate for a 5-year fixed residential mortgage with a 75% LTV in the UK.',
      },
      {
        id: 'gbp-ftse',
        label: 'FTSE 100 Historical Return',
        shortLabel: 'FTSE 100',
        val: '7.8%',
        numericVal: 7.8,
        unit: '%',
        target: 'investment',
        source: 'London Stock Exchange / FTSE Russell',
        sourceShort: 'FTSE Russell',
        frequency: 'Long-Term Total Return',
        patchInputs: { interestRate: 7.8, compoundFrequency: 'annually' },
        description: 'Compound annual total return (including dividend reinvestment) of the UK FTSE 100 index.',
      },
      {
        id: 'gbp-cpi',
        label: 'UK CPI Inflation Rate',
        shortLabel: 'UK CPI',
        val: '2.2%',
        numericVal: 2.2,
        unit: '%',
        target: 'inflation',
        source: 'Office for National Statistics (ONS)',
        sourceShort: 'ONS UK',
        frequency: 'Monthly Release',
        patchInputs: { annualInflationRate: 2.2 },
        description: 'UK 12-month Consumer Prices Index including owner occupiers’ housing costs.',
      },
    ],
  },

  EUR: {
    regionName: 'Eurozone',
    shortTag: 'Eurozone Rates',
    sourceSummary: 'European Central Bank (ECB) & Euribor',
    benchmarks: [
      {
        id: 'eur-ecb-rate',
        label: 'ECB Main Refinancing Rate',
        shortLabel: 'ECB Refi',
        val: '3.65%',
        numericVal: 3.65,
        unit: '%',
        target: 'loan',
        source: 'European Central Bank (ECB) Governing Council',
        sourceShort: 'ECB',
        frequency: 'Governing Council Cycle',
        patchInputs: { interestRate: 3.65, loanTermMonths: 36 },
        description: 'Key interest rate at which commercial banks borrow from the European Central Bank.',
      },
      {
        id: 'eur-euribor-12m',
        label: '12-Month Euribor Rate',
        shortLabel: '12M Euribor',
        val: '3.15%',
        numericVal: 3.15,
        unit: '%',
        target: 'mortgage',
        source: 'European Money Markets Institute (EMMI)',
        sourceShort: 'EMMI Euribor',
        frequency: 'Daily Interbank Rate',
        patchInputs: { interestRate: 3.15, loanTermYears: 20 },
        description: 'The standard interbank benchmark rate referenced by mortgages across Spain, Italy, Portugal, and France.',
      },
      {
        id: 'eur-eurostoxx',
        label: 'Euro Stoxx 50 Historical Return',
        shortLabel: 'Euro Stoxx',
        val: '8.4%',
        numericVal: 8.4,
        unit: '%',
        target: 'investment',
        source: 'STOXX European Blue Chip Index',
        sourceShort: 'STOXX 50',
        frequency: 'Historical CAGR',
        patchInputs: { interestRate: 8.4, compoundFrequency: 'annually' },
        description: 'Historical annualized total return of Europe’s leading 50 supersector leader equities.',
      },
      {
        id: 'eur-hicp',
        label: 'Euro Area HICP Inflation',
        shortLabel: 'Euro CPI',
        val: '2.2%',
        numericVal: 2.2,
        unit: '%',
        target: 'inflation',
        source: 'Eurostat Harmonised Index of Consumer Prices',
        sourceShort: 'Eurostat',
        frequency: 'Monthly Release',
        patchInputs: { annualInflationRate: 2.2 },
        description: 'Harmonised Index of Consumer Prices across the 20 Eurozone member states.',
      },
    ],
  },

  AED: {
    regionName: 'United Arab Emirates',
    shortTag: 'UAE Market Rates',
    sourceSummary: 'Central Bank of UAE (CBUAE) & EIBOR',
    benchmarks: [
      {
        id: 'aed-eibor',
        label: '3-Month EIBOR Benchmark',
        shortLabel: '3M EIBOR',
        val: '4.75%',
        numericVal: 4.75,
        unit: '%',
        target: 'loan',
        source: 'Central Bank of the United Arab Emirates (CBUAE)',
        sourceShort: 'CBUAE EIBOR',
        frequency: 'Daily Benchmark Rate',
        patchInputs: { interestRate: 4.75, loanTermMonths: 48 },
        description: 'Emirates Interbank Offered Rate used by UAE commercial banks for loans and auto financing.',
      },
      {
        id: 'aed-cbuae-base',
        label: 'CBUAE Overnight Base Rate',
        shortLabel: 'CBUAE Base',
        val: '4.90%',
        numericVal: 4.90,
        unit: '%',
        target: 'loan',
        source: 'Central Bank of the UAE',
        sourceShort: 'CBUAE',
        frequency: 'Fed Pegged Decisions',
        patchInputs: { interestRate: 4.90, loanTermMonths: 36 },
        description: 'Monetary policy base rate issued by the UAE Central Bank pegged to the US Federal Reserve.',
      },
      {
        id: 'aed-home-mortgage',
        label: 'UAE Home Mortgage Rate',
        shortLabel: 'UAE Mortgage',
        val: '5.15%',
        numericVal: 5.15,
        unit: '%',
        target: 'mortgage',
        source: 'UAE Retail Banking Average (ENBD, FAB, ADCB)',
        sourceShort: 'UAE Banks',
        frequency: 'Monthly Average',
        patchInputs: { interestRate: 5.15, loanTermYears: 25 },
        description: 'Average 3 to 5-year fixed home purchase mortgage rate across prime UAE lenders.',
      },
      {
        id: 'aed-cpi',
        label: 'UAE Headline Inflation Rate',
        shortLabel: 'UAE CPI',
        val: '2.1%',
        numericVal: 2.1,
        unit: '%',
        target: 'inflation',
        source: 'Federal Competitiveness and Statistics Centre (FCSC)',
        sourceShort: 'UAE FCSC',
        frequency: 'Monthly Release',
        patchInputs: { annualInflationRate: 2.1 },
        description: 'Annualized consumer inflation rate across Abu Dhabi, Dubai, and the Northern Emirates.',
      },
    ],
  },

  SAR: {
    regionName: 'Saudi Arabia',
    shortTag: 'Saudi Arabia Rates',
    sourceSummary: 'Saudi Central Bank (SAMA) & SAIBOR',
    benchmarks: [
      {
        id: 'sar-saibor',
        label: '3-Month SAIBOR Benchmark',
        shortLabel: '3M SAIBOR',
        val: '5.70%',
        numericVal: 5.70,
        unit: '%',
        target: 'loan',
        source: 'Saudi Central Bank (SAMA)',
        sourceShort: 'SAMA SAIBOR',
        frequency: 'Daily Interbank Rate',
        patchInputs: { interestRate: 5.70, loanTermMonths: 48 },
        description: 'Saudi Interbank Offered Rate used as benchmark for commercial loans and personal financing.',
      },
      {
        id: 'sar-sama-repo',
        label: 'SAMA Repo Rate',
        shortLabel: 'SAMA Repo',
        val: '5.50%',
        numericVal: 5.50,
        unit: '%',
        target: 'loan',
        source: 'Saudi Central Bank (SAMA)',
        sourceShort: 'SAMA',
        frequency: 'Pegged FOMC Updates',
        patchInputs: { interestRate: 5.50, loanTermMonths: 36 },
        description: 'Official repurchase agreement rate set by the Saudi Central Bank.',
      },
      {
        id: 'sar-home-finance',
        label: 'Murabaha / Ijara Real Estate Rate',
        shortLabel: 'KSA Mortgage',
        val: '5.45%',
        numericVal: 5.45,
        unit: '%',
        target: 'mortgage',
        source: 'Al Rajhi Bank / SNB Retail Financing Benchmark',
        sourceShort: 'KSA Lenders',
        frequency: 'Monthly Retail Rate',
        patchInputs: { interestRate: 5.45, loanTermYears: 20 },
        description: 'Typical Islamic Shariah-compliant real estate financing rate in the Kingdom.',
      },
      {
        id: 'sar-cpi',
        label: 'Saudi Arabia CPI Inflation',
        shortLabel: 'GASTAT CPI',
        val: '1.6%',
        numericVal: 1.6,
        unit: '%',
        target: 'inflation',
        source: 'General Authority for Statistics (GASTAT)',
        sourceShort: 'GASTAT',
        frequency: 'Monthly Release',
        patchInputs: { annualInflationRate: 1.6 },
        description: 'Headline Consumer Price Index inflation reported by Saudi GASTAT.',
      },
    ],
  },

  CAD: {
    regionName: 'Canada',
    shortTag: 'Canada Market Rates',
    sourceSummary: 'Bank of Canada (BoC) & Statistics Canada',
    benchmarks: [
      {
        id: 'cad-boc-policy',
        label: 'Bank of Canada Policy Rate',
        shortLabel: 'BoC Rate',
        val: '4.25%',
        numericVal: 4.25,
        unit: '%',
        target: 'loan',
        source: 'Bank of Canada Governing Council',
        sourceShort: 'Bank of Canada',
        frequency: 'Fixed Rate Announcements',
        patchInputs: { interestRate: 4.25, loanTermMonths: 36 },
        description: 'Target for the overnight rate set by the Bank of Canada governing Canadian retail prime rates.',
      },
      {
        id: 'cad-5y-fixed',
        label: '5-Yr Fixed Mortgage Benchmark',
        shortLabel: '5-Yr Mort.',
        val: '4.79%',
        numericVal: 4.79,
        unit: '%',
        target: 'mortgage',
        source: 'Big 6 Canadian Banks (RBC, TD, Scotiabank average)',
        sourceShort: 'Big 6 Banks',
        frequency: 'Weekly Quoted',
        patchInputs: { interestRate: 4.79, loanTermYears: 25 },
        description: 'Average 5-year fixed residential mortgage rate across major Canadian chartered banks.',
      },
      {
        id: 'cad-tsx',
        label: 'S&P/TSX Composite Historical Return',
        shortLabel: 'TSX Avg',
        val: '8.1%',
        numericVal: 8.1,
        unit: '%',
        target: 'investment',
        source: 'Toronto Stock Exchange / S&P Dow Jones',
        sourceShort: 'TSX Index',
        frequency: 'Long-Term CAGR',
        patchInputs: { interestRate: 8.1, compoundFrequency: 'annually' },
        description: 'Historical compound annual return of the benchmark Canadian equity index.',
      },
      {
        id: 'cad-cpi',
        label: 'Canada CPI Inflation',
        shortLabel: 'StatCan CPI',
        val: '2.5%',
        numericVal: 2.5,
        unit: '%',
        target: 'inflation',
        source: 'Statistics Canada Consumer Price Index',
        sourceShort: 'StatCan',
        frequency: 'Monthly Release',
        patchInputs: { annualInflationRate: 2.5 },
        description: '12-month percentage change in the Consumer Price Index in Canada.',
      },
    ],
  },

  AUD: {
    regionName: 'Australia',
    shortTag: 'Australia Market Rates',
    sourceSummary: 'Reserve Bank of Australia (RBA) & ABS',
    benchmarks: [
      {
        id: 'aud-rba-cash',
        label: 'RBA Cash Rate Target',
        shortLabel: 'RBA Cash',
        val: '4.35%',
        numericVal: 4.35,
        unit: '%',
        target: 'loan',
        source: 'Reserve Bank of Australia (RBA) Board',
        sourceShort: 'RBA Board',
        frequency: 'Monthly Board Meeting',
        patchInputs: { interestRate: 4.35, loanTermMonths: 36 },
        description: 'The official cash rate target determining variable lending rates across Australian banks.',
      },
      {
        id: 'aud-variable-home',
        label: 'Variable Home Loan Benchmark',
        shortLabel: 'Variable Home',
        val: '6.15%',
        numericVal: 6.15,
        unit: '%',
        target: 'mortgage',
        source: 'Major Australian Banks (CBA, Westpac, ANZ, NAB average)',
        sourceShort: 'Big 4 Banks',
        frequency: 'Monthly Retail Average',
        patchInputs: { interestRate: 6.15, loanTermYears: 30 },
        description: 'Average discounted variable interest rate for owner-occupier principal and interest home loans.',
      },
      {
        id: 'aud-asx',
        label: 'S&P/ASX 200 Total Return',
        shortLabel: 'ASX 200',
        val: '9.2%',
        numericVal: 9.2,
        unit: '%',
        target: 'investment',
        source: 'Australian Securities Exchange / S&P',
        sourceShort: 'ASX Index',
        frequency: 'Historical CAGR',
        patchInputs: { interestRate: 9.2, compoundFrequency: 'annually' },
        description: 'Long-term compound annual return including franked dividends of the top 200 ASX companies.',
      },
      {
        id: 'aud-cpi',
        label: 'Australia Headline CPI Inflation',
        shortLabel: 'ABS CPI',
        val: '3.8%',
        numericVal: 3.8,
        unit: '%',
        target: 'inflation',
        source: 'Australian Bureau of Statistics (ABS)',
        sourceShort: 'ABS Australia',
        frequency: 'Quarterly & Monthly Data',
        patchInputs: { annualInflationRate: 3.8 },
        description: 'Consumer Price Index inflation released by the Australian Bureau of Statistics.',
      },
    ],
  },
};

export function getRegionalMarketData(currency: CurrencyCode): RegionalMarketData {
  return REGIONAL_MARKET_DATA[currency] || REGIONAL_MARKET_DATA.USD;
}

export function getLastUpdatedTimestamp(): string {
  return 'Updated this week · Official Central Bank Feeds';
}

export async function fetchLiveMarketRates(currency: CurrencyCode): Promise<{
  benchmarks: MarketBenchmark[];
  lastUpdated: string;
}> {
  const data = getRegionalMarketData(currency);
  return {
    benchmarks: data.benchmarks,
    lastUpdated: getLastUpdatedTimestamp(),
  };
}
